spring:
  datasource:
    url: jdbc:postgresql://localhost:5565/library_db
    username: postgres
    password: root

  flyway:
    locations: classpath:migration

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080